//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2013.02.09 at 04:11:15 PM CET
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.jcp.org/jcr/sv/1.0",
        elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED,
        xmlns = {
            @XmlNs(prefix = "sv", namespaceURI = "http://www.jcp.org/jcr/sv/1.0")
        }
)
package nl.openweb.hippo.groovy.model.jaxb;

import javax.xml.bind.annotation.XmlNs;